#ifndef KRX_KOSPI_FUTURES_HPP
#define KRX_KOSPI_FUTURES_HPP

struct KrxFuturesDesc{
	unsigned char datatype[2];
	unsigned char infotype[2];
	unsigned char markettype[1];
	unsigned char stocksnum[5];
	unsigned char tradeday[8];
	char krcode[12];
	unsigned char seq[6];
	char derivativeid[10];
	char krcodeshort[9];
	char koreanname[80];
	char koreannameshort[40];
	char englishname[80];
	char englishnameshort[40];
	unsigned char issuedate[8];
	unsigned char expirydate[8];
	unsigned char longorshortspread[1];
	unsigned char cashorasset[1];
	unsigned char upperlimitsign[1];
	unsigned char upperlimitprice[12];
	unsigned char lowerlimitsign[1];
	unsigned char lowerlimitprice[12];
	unsigned char baseprice[12];
	unsigned char underlyingid[3];
	unsigned char americanoreuropean[1];
	unsigned char spreadtype[2];
	unsigned char spreadnearbycode[12];
	unsigned char spreaddistantcode[12];
	unsigned char lasttradedate[8];
	unsigned char lastpaydate[8];
	unsigned char monthtype[1];
	unsigned char lastexerdate[8];
	unsigned char strikeprice[17];
	unsigned char adjusttype[1];
	unsigned char tradingunit[17];
	unsigned char tradingmultip[21];
	unsigned char constructiontype[1];
	unsigned char issuetype[1];
	unsigned char atmprice[12];
	unsigned char adjustreason[2];
	char underlyingkrcode[12];
	unsigned char underlyinglastprice[12];
	unsigned char timetomatdays[7];
	unsigned char adjustbaseprice[17];
	unsigned char basepricetype[2];
	unsigned char dealbasepricetype[1];
	unsigned char lastadjpricesign[1];
	unsigned char lastadjprice[17];
	unsigned char blocktradeyn[1];
	unsigned char prevmarginbaseprice[17];
	unsigned char prevmarginbasepricetype[2];
	unsigned char settledtheoreticprice[15];
	unsigned char basethereticprice[15];
	unsigned char prevsettledprice[17];
	unsigned char prohibitedtradeyn[1];
	unsigned char circuitbreakersupperlimit[12];
	unsigned char circuitbreakerslowerlimit[12];
	unsigned char inquirystrikeprice[17];
	unsigned char moneynesstype[1];
	unsigned char lastdayyn[1];
	unsigned char exdividendprice[15];
	unsigned char lastpricesign[1];
	unsigned char lastprice[12];
	unsigned char lastpricetype[1];
	unsigned char tradeprice[12];
	unsigned char highpricesign[1];
	unsigned char highprice[12];
	unsigned char lowpricesign[1];
	unsigned char lowprice[12];
	unsigned char firstcontractedtime[8];
	unsigned char lastcontractedtime[8];
	unsigned char lastsettlepricetype[2];
	unsigned char settletheordiffsign[1];
	unsigned char settletheoreticdiff[12];
	unsigned char prevdayunsettledcontractnum[10];
	unsigned char prevbestaskprice[12];
	unsigned char prevbestbidsign[1];
	unsigned char prevbestbidprice[12];
	unsigned char impliedvolatility[10];
	unsigned char underlyingmaxdelta[6];
	unsigned char alltimehighestsign[1];
	unsigned char alltimehighestprice[12];
	unsigned char alltimelowestsign[1];
	unsigned char alltimelowestprice[12];
	unsigned char annualhighestsign[1];
	unsigned char annualhighestprice[12];
	unsigned char annuallowestsign[1];
	unsigned char annuallowestprice[12];
	unsigned char alltimelowestdate[8];
	unsigned char annualhighestdate[8];
	unsigned char annuallowestdate[8];
	unsigned char annualbasedaysnum[8];
	unsigned char monthlytradedaysnum[8];
	unsigned char yearlytradedaysnum[8];
	unsigned char prevdaycontractsnum[16];
	unsigned char prevdayquantity[12];
	unsigned char prevdaytotalamount[22];
	unsigned char prevdayblocktradequantity[12];
	unsigned char prevdayblocktradeamount[22];
	unsigned char rate_cd[6];
	unsigned char maxunsettledcontractsnum[8];
	unsigned char affiliatedcommoditygroup[4];
	unsigned char limitorderconditioncode[1];
	unsigned char marketorderconditioncode[1];
	unsigned char conditionallimitorderconditioncode[1];
	unsigned char bestlimitorderconditioncode[1];
	unsigned char subjectedtoefpyn[1];
	unsigned char subjectedtoflexyn[1];
	unsigned char prevdayefpquantity[12];
	unsigned char prevdayefpamount[22];
	unsigned char closureyn[1];
	unsigned char filler[133];
	unsigned char eot[1];
};

struct KrxFuturesBestQuotation{
	unsigned char datatype[2];
	unsigned char infotype[2];
	unsigned char markettype[1];
	char krcode[12];
	unsigned char seq[2];
	unsigned char marketstatecode[2];
	unsigned char bidtotalquantity[6];
	unsigned char bid1sign[1];
	unsigned char bid1price[5];
	unsigned char bid1quantity[6];
	unsigned char bid2sign[1];
	unsigned char bid2price[5];
	unsigned char bid2quantity[6];
	unsigned char bid3sign[1];
	unsigned char bid3price[5];
	unsigned char bid3quantity[6];
	unsigned char bid4sign[1];
	unsigned char bid4price[5];
	unsigned char bid4quantity[6];
	unsigned char bid5sign[1];
	unsigned char bid5price[5];
	unsigned char bid5quantity[6];
	unsigned char asktotalquantity[6];
	unsigned char ask1sign[1];
	unsigned char ask1price[5];
	unsigned char ask1quantity[6];
	unsigned char ask2sign[1];
	unsigned char ask2price[5];
	unsigned char ask2quantity[6];
	unsigned char ask3sign[1];
	unsigned char ask3price[5];
	unsigned char ask3quantity[6];
	unsigned char ask4sign[1];
	unsigned char ask4price[5];
	unsigned char ask4quantity[6];
	unsigned char ask5sign[1];
	unsigned char ask5price[5];
	unsigned char ask5quantity[6];
	unsigned char bidtotalvalidnum[5];
	unsigned char bid1totalvalidnum[4];
	unsigned char bid2totalvalidnum[4];
	unsigned char bid3totalvalidnum[4];
	unsigned char bid4totalvalidnum[4];
	unsigned char bid5totalvalidnum[4];
	unsigned char asktotalvalidnum[5];
	unsigned char ask1totalvalidnum[4];
	unsigned char ask2totalvalidnum[4];
	unsigned char ask3totalvalidnum[4];
	unsigned char ask4totalvalidnum[4];
	unsigned char ask5totalvalidnum[4];
	unsigned char timestamp[8];
	unsigned char expectedpricesign[1];
	unsigned char expectedprice[5];
	unsigned char eot[1];
};

struct KrxFuturesTrade{
	unsigned char datatype[2];
	unsigned char infotype[2];
	unsigned char markettype[1];
	char krcode[12];
	unsigned char seq[2];
	unsigned char currentpricesign[1];
	unsigned char currentprice[5];
	unsigned char tradequantity[6];
	unsigned char tradetype[2];
	unsigned char timestamp[8];
	unsigned char closesttradeprice[5];
	unsigned char distanttradeprice[5];
	unsigned char marketpricesign[1];
	unsigned char marketprice[5];
	unsigned char highpricesign[1];
	unsigned char highprice[5];
	unsigned char lowpricesign[1];
	unsigned char lowprice[5];
	unsigned char lastpricesign[1];
	unsigned char lastprice[5];
	unsigned char accumtradequantity[7];
	unsigned char accumtradeamount[12];
	unsigned char eot[1];
};

struct KrxFuturesTradeBestQuotation{
	unsigned char datatype[2];
	unsigned char infotype[2];
	unsigned char markettype[1];
	char krcode[12];
	unsigned char seq[2];
	unsigned char currentpricesign[1];
	unsigned char currentprice[5];
	unsigned char tradequantity[6];
	unsigned char tradetype[2];
	unsigned char timestamp[8];
	unsigned char closesttradeprice[5];
	unsigned char distanttradeprice[5];
	unsigned char marketpricesign[1];
	unsigned char marketprice[5];
	unsigned char highpricesign[1];
	unsigned char highprice[5];
	unsigned char lowpricesign[1];
	unsigned char lowprice[5];
	unsigned char lastpricesign[1];
	unsigned char lastprice[5];
	unsigned char accumtradequantity[7];
	unsigned char accumtradeamount[12];
	unsigned char marketstatecode[2];
	unsigned char bidtotalquantity[6];
	unsigned char bid1sign[1];
	unsigned char bid1price[5];
	unsigned char bid1quantity[6];
	unsigned char bid2sign[1];
	unsigned char bid2price[5];
	unsigned char bid2quantity[6];
	unsigned char bid3sign[1];
	unsigned char bid3price[5];
	unsigned char bid3quantity[6];
	unsigned char bid4sign[1];
	unsigned char bid4price[5];
	unsigned char bid4quantity[6];
	unsigned char bid5sign[1];
	unsigned char bid5price[5];
	unsigned char bid5quantity[6];
	unsigned char asktotalquantity[6];
	unsigned char ask1sign[1];
	unsigned char ask1price[5];
	unsigned char ask1quantity[6];
	unsigned char ask2sign[1];
	unsigned char ask2price[5];
	unsigned char ask2quantity[6];
	unsigned char ask3sign[1];
	unsigned char ask3price[5];
	unsigned char ask3quantity[6];
	unsigned char ask4sign[1];
	unsigned char ask4price[5];
	unsigned char ask4quantity[6];
	unsigned char ask5sign[1];
	unsigned char ask5price[5];
	unsigned char ask5quantity[6];
	unsigned char bidtotalvalidnum[5];
	unsigned char bid1totalvalidnum[4];
	unsigned char bid2totalvalidnum[4];
	unsigned char bid3totalvalidnum[4];
	unsigned char bid4totalvalidnum[4];
	unsigned char bid5totalvalidnum[4];
	unsigned char asktotalvalidnum[5];
	unsigned char ask1totalvalidnum[4];
	unsigned char ask2totalvalidnum[4];
	unsigned char ask3totalvalidnum[4];
	unsigned char ask4totalvalidnum[4];
	unsigned char ask5totalvalidnum[4];
	unsigned char eot[1];
};

struct KrxFuturesEnd{
	unsigned char datatype[2];
	unsigned char infotype[2];
	unsigned char markettype[1];
	char krcode[12];
	unsigned char seq[2];
	unsigned char endpricesign[1];
	unsigned char endprice[5];
	unsigned char endpricecode[1];
	unsigned char accumtradequantity[7];
	unsigned char accumtradeamount[12];
	unsigned char bidtotalquantity[6];
	unsigned char bid1sign[1];
	unsigned char bid1price[5];
	unsigned char bid1quantity[6];
	unsigned char bid2sign[1];
	unsigned char bid2price[5];
	unsigned char bid2quantity[6];
	unsigned char bid3sign[1];
	unsigned char bid3price[5];
	unsigned char bid3quantity[6];
	unsigned char bid4sign[1];
	unsigned char bid4price[5];
	unsigned char bid4quantity[6];
	unsigned char bid5sign[1];
	unsigned char bid5price[5];
	unsigned char bid5quantity[6];
	unsigned char asktotalquantity[6];
	unsigned char ask1sign[1];
	unsigned char ask1price[5];
	unsigned char ask1quantity[6];
	unsigned char ask2sign[1];
	unsigned char ask2price[5];
	unsigned char ask2quantity[6];
	unsigned char ask3sign[1];
	unsigned char ask3price[5];
	unsigned char ask3quantity[6];
	unsigned char ask4sign[1];
	unsigned char ask4price[5];
	unsigned char ask4quantity[6];
	unsigned char ask5sign[1];
	unsigned char ask5price[5];
	unsigned char ask5quantity[6];
	unsigned char bidtotalvalidnum[5];
	unsigned char bid1totalvalidnum[4];
	unsigned char bid2totalvalidnum[4];
	unsigned char bid3totalvalidnum[4];
	unsigned char bid4totalvalidnum[4];
	unsigned char bid5totalvalidnum[4];
	unsigned char asktotalvalidnum[5];
	unsigned char ask1totalvalidnum[4];
	unsigned char ask2totalvalidnum[4];
	unsigned char ask3totalvalidnum[4];
	unsigned char ask4totalvalidnum[4];
	unsigned char ask5totalvalidnum[4];
	unsigned char eot[1];
};

struct KrxFuturesMarketManage{
	unsigned char datatype[2];
	unsigned char infotype[2];
	unsigned char markettype[1];
	unsigned char timestamp[8];
	unsigned char marketmanagecode[3];
	unsigned char stockid[10];
	char krcode[12];
	unsigned char seq[2];
	unsigned char marketstatecode[2];
	unsigned char bidaskexistyn[1];
	unsigned char bidtotalquantity[6];
	unsigned char bid1sign[1];
	unsigned char bid1price[5];
	unsigned char bid1quantity[6];
	unsigned char bid2sign[1];
	unsigned char bid2price[5];
	unsigned char bid2quantity[6];
	unsigned char bid3sign[1];
	unsigned char bid3price[5];
	unsigned char bid3quantity[6];
	unsigned char bid4sign[1];
	unsigned char bid4price[5];
	unsigned char bid4quantity[6];
	unsigned char bid5sign[1];
	unsigned char bid5price[5];
	unsigned char bid5quantity[6];
	unsigned char asktotalquantity[6];
	unsigned char ask1sign[1];
	unsigned char ask1price[5];
	unsigned char ask1quantity[6];
	unsigned char ask2sign[1];
	unsigned char ask2price[5];
	unsigned char ask2quantity[6];
	unsigned char ask3sign[1];
	unsigned char ask3price[5];
	unsigned char ask3quantity[6];
	unsigned char ask4sign[1];
	unsigned char ask4price[5];
	unsigned char ask4quantity[6];
	unsigned char ask5sign[1];
	unsigned char ask5price[5];
	unsigned char ask5quantity[6];
	unsigned char bidtotalvalidnum[5];
	unsigned char bid1totalvalidnum[4];
	unsigned char bid2totalvalidnum[4];
	unsigned char bid3totalvalidnum[4];
	unsigned char bid4totalvalidnum[4];
	unsigned char bid5totalvalidnum[4];
	unsigned char asktotalvalidnum[5];
	unsigned char ask1totalvalidnum[4];
	unsigned char ask2totalvalidnum[4];
	unsigned char ask3totalvalidnum[4];
	unsigned char ask4totalvalidnum[4];
	unsigned char ask5totalvalidnum[4];
	unsigned char eot[1];
};

struct KrxFuturesSpace{
	unsigned char datatype[2];
	unsigned char infotype[2];
	unsigned char markettype[1];
	unsigned char eot[1];
};

struct KrxFuturesDistribute{
	unsigned char datatype[2];
	unsigned char infotype[2];
	unsigned char markettype[1];
	char krcode[12];
	unsigned char seq[2];
	unsigned char distribute_startorend[1];
	unsigned char distributetype[1];
	unsigned char distributeendtime[8];
	unsigned char eot[1];
};

struct KrxFuturesInvestorData{
	unsigned char datatype[2];
	unsigned char infotype[2];
	unsigned char markettype[1];
	unsigned char createdate[8];
	unsigned char createtime[6];
	unsigned char investordatatype[2];
	unsigned char stockid[10];
	unsigned char investortype[4];
	unsigned char bidsettledquantity[9];
	unsigned char asksettledquantity[9];
	unsigned char bidsettledamount[18];
	unsigned char asksettledamount[18];
	unsigned char bidspreadedquantity[9];
	unsigned char askspreadedquantity[9];
	unsigned char bidspreadedamount[18];
	unsigned char askspreadedamount[18];
	unsigned char eot[1];
};

struct KrxFuturesUnsettled{
	unsigned char datatype[2];
	unsigned char infotype[2];
	unsigned char markettype[1];
	char krcode[12];
	unsigned char seq[2];
	unsigned char unsettledtype[2];
	unsigned char tradedate[8];
	unsigned char unsettledamount[9];
	unsigned char eot[1];
};

struct KrxFuturesSettled{
	unsigned char datatype[2];
	unsigned char infotype[2];
	unsigned char markettype[1];
	char krcode[12];
	unsigned char seq[2];
	unsigned char settledprice[16];
	unsigned char settledpricetype[1];
	unsigned char finalsettledprice[16];
	unsigned char finalsettledpricetype[1];
	unsigned char eot[1];
};

struct KrxFuturesMarketpriceRecovery{
	unsigned char datatype[2];
	unsigned char infotype[2];
	unsigned char markettype[1];
	char krcode[12];
	unsigned char seq[2];
	unsigned char currentpricesign[1];
	unsigned char currentprice[5];
	unsigned char closesttradeprice[5];
	unsigned char distanttradeprice[5];
	unsigned char marketpricesign[1];
	unsigned char marketprice[5];
	unsigned char highpricesign[1];
	unsigned char highprice[5];
	unsigned char lowpricesign[1];
	unsigned char lowprice[5];
	unsigned char unsettledamount[9];
	unsigned char accumtradequantity[7];
	unsigned char accumtradeamount[12];
	unsigned char ask1sign[1];
	unsigned char ask1price[5];
	unsigned char ask1quantity[6];
	unsigned char ask1num[4];
	unsigned char bid1sign[1];
	unsigned char bid1price[5];
	unsigned char bid1quantity[6];
	unsigned char bid1num[4];
	unsigned char ask2sign[1];
	unsigned char ask2price[5];
	unsigned char ask2quantity[6];
	unsigned char ask2num[4];
	unsigned char bid2sign[1];
	unsigned char bid2price[5];
	unsigned char bid2quantity[6];
	unsigned char bid2num[4];
	unsigned char ask3sign[1];
	unsigned char ask3price[5];
	unsigned char ask3quantity[6];
	unsigned char ask3num[4];
	unsigned char bid3sign[1];
	unsigned char bid3price[5];
	unsigned char bid3quantity[6];
	unsigned char bid3num[4];
	unsigned char ask4sign[1];
	unsigned char ask4price[5];
	unsigned char ask4quantity[6];
	unsigned char ask4num[4];
	unsigned char bid4sign[1];
	unsigned char bid4price[5];
	unsigned char bid4quantity[6];
	unsigned char bid4num[4];
	unsigned char ask5sign[1];
	unsigned char ask5price[5];
	unsigned char ask5quantity[6];
	unsigned char ask5num[4];
	unsigned char bid5sign[1];
	unsigned char bid5price[5];
	unsigned char bid5quantity[6];
	unsigned char bid5num[4];
	unsigned char asktotalquantity[6];
	unsigned char asktotalnum[5];
	unsigned char bidtotalquantity[6];
	unsigned char bidtotalnum[5];
	unsigned char marketstatetype[2];
	unsigned char marketmanagetype[3];
	unsigned char expectedpricesign[1];
	unsigned char expectedprice[5];
	unsigned char eot[1];
};

struct KrxFuturesPolling{
	unsigned char datatype[2];
	unsigned char infotype[2];
	unsigned char markettype[1];
	unsigned char timestampHHSS[4];
	unsigned char mainorbackup[2];
	unsigned char filler[8];
	unsigned char eot[1];
};

struct KrxFuturesOpenMarketManage{
	unsigned char datatype[2];
	unsigned char infotype[2];
	unsigned char markettype[1];
	unsigned char timestamp[8];
	unsigned char marketmanagecode[3];
	unsigned char stockid[10];
	char krcode[12];
	unsigned char seq[3];
	unsigned char marketstatecode[2];
	unsigned char eot[1];
};
#endif